### ISSUE TITLE
clean install results in nvm_prepend_path error

### ISSUE THREAD

**Issue by heikomat** [wzrdtales/nvm-ng#1]
`--fast-reuse` is not working with the current version of nvm-ng, it breaks my terminal.

without `--fast-reuse` everything works

the version from here: https://github.com/wzrdtales/nvm/tree/fastPath works with `--fast-reuse`

- Operating system and version: OS X 10.12.6

- `nvm debug` output:
<details>

```sh
nvm --version: v0.33.8
$TERM_PROGRAM: iTerm.app
$SHELL: /bin/zsh
$SHLVL: 1
$HOME: /Users/heiko
$NVM_DIR: '$HOME/.nvm'
$PATH: $NVM_DIR/versions/node/v9.8.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
$PREFIX: ''
$NPM_CONFIG_PREFIX: ''
$NVM_NODEJS_ORG_MIRROR: ''
$NVM_IOJS_ORG_MIRROR: ''
shell version: 'zsh 5.2 (x86_64-apple-darwin16.0)'
uname -a: 'Darwin 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64'
OS version: Mac 10.12.6 16G1114
curl: /usr/bin/curl, curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
wget: not found
git: /usr/bin/git, git version 2.11.0 (Apple Git-81)
grep: grep: aliased to grep  --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} (grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}), grep (BSD grep) 2.5.1-FreeBSD
awk: /usr/bin/awk, awk version 20070501
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: /usr/bin/sed,
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
cut: /usr/bin/cut,
basename: illegal option -- -
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
basename: /usr/bin/basename,
rm: illegal option -- -
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
rm: /bin/rm,
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory ...
mkdir: /bin/mkdir,
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
xargs: /usr/bin/xargs,
nvm current: v9.8.0
which node: $NVM_DIR/versions/node/v9.8.0/bin/node
which iojs: iojs not found
which npm: $NVM_DIR/versions/node/v9.8.0/bin/npm
npm config get prefix: $NVM_DIR/versions/node/v9.8.0
npm root -g: $NVM_DIR/versions/node/v9.8.0/lib/node_modules
```
</details>

- `nvm ls` output:
<details>

```sh
->       v9.8.0
default -> node (-> v9.8.0)
node -> stable (-> v9.8.0) (default)
stable -> 9.8 (-> v9.8.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.8.7 (-> N/A)
lts/boron -> v6.13.1 (-> N/A)
lts/carbon -> v8.10.0 (-> N/A)
```
</details>

- How did you install `nvm`? (e.g. install script in readme, Homebrew):

   install-script

- What steps did you perform?

   I executed the install-script, opened a new terminal, ran `nvm install node`, added the `--fast-reuse` flag to the nvm initialization in my `~/.zshrc` and opened another terminal

- What happened?

  The new terminal printed `nvm_auto:23: command not found: nvm_prepend_path`, and no commands are found in that terminal

![bildschirmfoto 2018-03-12 um 10 17 15](https://user-images.githubusercontent.com/20770029/37275395-5c1e5852-25df-11e8-9684-3b0e58b760f2.png)

- What did you expect to happen?

   I expected nvm to work with the `--fast-reuse` flag. It works, but only without the flag

- Is there anything in any of your profile files (`.bashrc`, `.bash_profile`, `.zshrc`, etc) that modifies the `PATH`?

  No

**Comment by wzrdtales** [comment]
I have merged the latest changes of the original nvm branch as well, that might broke something, gonna look at this.

**Comment by wzrdtales** [comment]
It has worked on my side though, but that is not a proof that it works :)

**Comment by wzrdtales** [comment]
Here we go, fixed it :)

**Comment by heikomat** [comment]
yep, this fixed it, though i had to edit the `~/.nvm/.git/config` to be able to pull the changes from master. Could you make a new release with this, so it can be installed with the install-script?

**Comment by wzrdtales** [comment]
did so, just quickly fixed a bug that i noticed that is exclusively to zsh. since zsh do not split spaces by default. have just released this with 0.33.10 alltogether :)

**Comment by heikomat** [comment]
nice, thank you! :)

**Comment by wzrdtales** [comment]
Since you made this popping up for me again, I invested some time to make tests pass again, fix some bugs and also submit a plugin  to oh my zsh:

https://github.com/robbyrussell/oh-my-zsh/pull/6671

**Comment by heikomat** [comment]
oh damn! nice :)
